apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: workshop
    component: backend
spec:
  type: ClusterIP
  selector:
    app: workshop
    component: api
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP