apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: workshop
    component: postgres
spec:
  type: ClusterIP
  selector:
    app: workshop
    component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP